// ═══════════════════════════════════════════════════════════
//  UniGuide — Shared Data Module
//  All majors, universities, scholarships, courses
// ═══════════════════════════════════════════════════════════

// ───────────────────────────────────────────────────────────
//  MAJORS DATABASE  (~800 majors across all categories)
// ───────────────────────────────────────────────────────────
const MAJORS = {
  "Engineering": [
    // Mechanical
    "Mechanical Engineering","Mechanical Engineering and Management","Mechatronics Engineering",
    "Robotics Engineering","Manufacturing Engineering","Aerospace Engineering",
    "Aeronautical Engineering","Astronautical Engineering","Automotive Engineering",
    "Biomechanical Engineering","Thermal Engineering","Fluid Mechanics Engineering",
    "Materials Engineering","Metallurgical Engineering","Structural Engineering",
    "Industrial Engineering","Systems Design Engineering","Engineering Physics",
    // Electrical / Computer
    "Electrical Engineering","Computer Engineering","Software Engineering",
    "Electrical and Computer Engineering","Electronic Systems Engineering",
    "Communications Engineering","Photonics Engineering","Power Systems Engineering",
    "Control Systems Engineering","Embedded Systems Engineering","Network Engineering",
    "Telecommunications Engineering","Microelectronics Engineering","VLSI Design",
    // Civil / Environmental
    "Civil Engineering","Environmental Engineering","Geological Engineering",
    "Geotechnical Engineering","Transportation Engineering","Urban Engineering",
    "Structural Engineering","Water Resources Engineering","Environmental Systems Engineering",
    "Construction Engineering","Infrastructure Engineering","Mining Engineering",
    "Petroleum Engineering","Ocean Engineering","Coastal Engineering",
    // Chemical / Biomedical
    "Chemical Engineering","Biochemical Engineering","Biomedical Engineering",
    "Bioengineering","Biomolecular Engineering","Process Engineering",
    "Polymer Engineering","Nuclear Engineering","Nanotechnology Engineering",
    "Food Engineering","Agricultural Engineering","Pulp and Paper Engineering",
    "Safety Engineering","Reliability Engineering","Quality Engineering",
    // Management / Other
    "Engineering and Business","Engineering Management","Sustainable Energy Engineering",
    "Renewable Energy Engineering","Fire Safety Engineering","Architectural Engineering",
    "Surveying Engineering","Geomatics Engineering","Engineering Science",
    "Honours Engineering","Integrated Engineering","Collaborative Engineering"
  ],
  "Computer Science & IT": [
    "Computer Science","Computer Science (Co-op)","Computer Science and Mathematics",
    "Computer Science and Statistics","Computer Science and Business",
    "Computer Science and Psychology","Computer Science and Philosophy",
    "Software Engineering","Data Science","Artificial Intelligence",
    "Machine Learning","Computational Intelligence","Cognitive Science",
    "Human-Computer Interaction","Computer Graphics","Game Development",
    "Game Design and Development","Cybersecurity","Information Security",
    "Network Security","Digital Forensics","Cloud Computing",
    "Web Development","Mobile Computing","Database Systems",
    "Bioinformatics","Computational Biology","Health Informatics",
    "Geographic Information Systems","Information Technology","Computer Systems",
    "Computing and Financial Management","Computing Science","Applied Computing",
    "Information Systems","Management Information Systems","Digital Technology",
    "Computing Technology","Computer Networking","Wireless Networks",
    "Internet of Things","Embedded Systems","Computer Animation",
    "Visual Effects","Digital Media","Interactive Arts and Technology",
    "Business Technology Management","Technology Management","IT Management",
    "Computing Arts","Computing Business","Honours Computer Science"
  ],
  "Health Sciences": [
    // Medicine-adjacent
    "Health Sciences","Health Studies","Health and Society","Global Health",
    "Public Health","Community Health","Indigenous Health","Environmental Health",
    "Mental Health","Occupational Health","Health Administration","Health Informatics",
    "Health Policy","Health Economics","Health Communications",
    // Nursing
    "Nursing","Bachelor of Science in Nursing","Collaborative Nursing",
    "Practical Nursing","Mental Health Nursing","Pediatric Nursing",
    "Neonatal Nursing","Forensic Nursing","Community Health Nursing",
    // Allied Health
    "Kinesiology","Exercise Science","Athletic Therapy","Sport Medicine",
    "Sport and Recreation Management","Recreation Therapy","Leisure Studies",
    "Occupational Therapy","Physical Therapy","Physiotherapy",
    "Respiratory Therapy","Medical Radiation Sciences","Medical Imaging",
    "Radiation Therapy","Nuclear Medicine Technology","Sonography",
    "Paramedicine","Emergency Medical Care","Paramedic Studies",
    // Pharmacy / Nutrition
    "Pharmacy","Pharmaceutical Sciences","Pharmacology","Toxicology",
    "Nutrition","Nutritional Sciences","Food and Nutrition","Dietetics",
    "Food Science","Food Biotechnology","Food Safety",
    // Dental / Optometry
    "Dental Hygiene","Dental Assisting","Dental Technology",
    "Optometry","Vision Science","Audiology","Speech-Language Pathology",
    // Biomedical
    "Biomedical Sciences","Medical Laboratory Science","Medical Laboratory Technology",
    "Biochemistry","Molecular Biology","Cellular Biology","Microbiology",
    "Immunology","Virology","Genetics","Genomics","Proteomics",
    "Epidemiology","Biostatistics","Anatomy","Physiology",
    "Pathology","Medical Science","Pre-Medicine","Pre-Dentistry"
  ],
  "Business": [
    // Core Business
    "Business Administration","Commerce","Bachelor of Commerce","Business Management",
    "Business and Society","International Business","Global Business",
    "Business Economics","Business Analytics","Business Intelligence",
    "Entrepreneurship","Innovation and Entrepreneurship","Social Entrepreneurship",
    // Finance / Accounting
    "Finance","Financial Management","Financial Economics","Financial Mathematics",
    "Accounting","Professional Accounting","Managerial Accounting","CPA Stream",
    "Actuarial Science","Insurance and Risk Management","Financial Planning",
    "Investment Management","Banking","Corporate Finance","Quantitative Finance",
    "Financial Engineering","Real Estate","Real Estate Management",
    // Marketing / Sales
    "Marketing","Digital Marketing","Marketing Management","Brand Management",
    "Advertising","Public Relations","Communications and Marketing",
    "Consumer Behaviour","Market Research","Sports Marketing","Retail Management",
    // Management / HR
    "Human Resource Management","Organizational Behaviour","Leadership",
    "Operations Management","Supply Chain Management","Logistics",
    "Project Management","Strategic Management","Change Management",
    "Non-Profit Management","Healthcare Administration","Sports Management",
    // Hospitality / Tourism
    "Hospitality Management","Hotel Management","Restaurant Management",
    "Tourism Management","Event Management","Recreation Management",
    "Travel and Tourism","Aviation Management",
    // Other Business
    "Economics","Agricultural Economics","Environmental Economics","Behavioural Economics",
    "Political Economy","Development Economics","International Economics",
    "Business Law","Taxation","Customs and International Trade"
  ],
  "Arts & Humanities": [
    // English / Writing
    "English","English Literature","English Language and Literature","English and Creative Writing",
    "Creative Writing","Professional Writing","Technical Writing","Journalism",
    "Digital Journalism","Broadcasting","Media Studies","Film Studies",
    "Theatre","Drama","Dramatic Arts","Performance Studies",
    // Languages
    "French","Linguistics","Spanish","German","Italian","Portuguese","Russian",
    "Arabic","Mandarin","Japanese","Korean","Hindi","Urdu",
    "Classical Studies","Latin","Ancient Greek","Sanskrit",
    "Translation Studies","Interpretation","Sign Language Interpretation",
    // History / Philosophy
    "History","Canadian History","World History","Ancient History","Medieval History",
    "Philosophy","Applied Ethics","Logic","Philosophy of Mind","Philosophy of Science",
    "Religious Studies","Theology","Islamic Studies","Jewish Studies",
    "Catholic Studies","Indigenous Studies","Cultural Studies",
    // Fine Arts
    "Fine Arts","Visual Arts","Studio Arts","Art History","Art History and Museum Studies",
    "Drawing and Painting","Sculpture","Printmaking","Ceramics","Textiles",
    "Photography","Digital Arts","Animation","Graphic Design","Illustration",
    "Interior Design","Fashion Design","Industrial Design","Product Design",
    "Architecture","Urban Planning and Design","Landscape Architecture",
    // Music
    "Music","Music Performance","Music Education","Music Theory","Musicology",
    "Music Technology","Sound Design","Audio Production","Music Business",
    "Music Composition","Jazz Studies","World Music","Electronic Music",
    // Other Humanities
    "Philosophy and Classical Studies","Arts and Science","Liberal Arts",
    "Interdisciplinary Studies","General Arts","Humanities"
  ],
  "Social Sciences": [
    // Psychology
    "Psychology","Applied Psychology","Clinical Psychology","Forensic Psychology",
    "Industrial-Organizational Psychology","Sports Psychology","Neuropsychology",
    "Child Psychology","Health Psychology","Counselling Psychology",
    "Cognitive Psychology","Social Psychology","Developmental Psychology",
    // Sociology / Anthropology
    "Sociology","Social Work","Child and Youth Care","Family Studies",
    "Women's and Gender Studies","Sexuality Studies","LGBTQ+ Studies",
    "Race and Ethnic Studies","Disability Studies","Social Justice",
    "Anthropology","Cultural Anthropology","Biological Anthropology","Archaeology",
    // Political Science / Law
    "Political Science","International Relations","International Studies",
    "Public Policy","Public Administration","Law and Society",
    "Criminology","Criminal Justice","Police Studies","Corrections",
    "Security Studies","Peace and Conflict Studies","Human Rights",
    // Geography / Urban
    "Geography","Human Geography","Physical Geography","Urban Geography",
    "Urban Studies","City Planning","Community Development",
    "Regional Planning","Sustainable Communities","Environmental Planning",
    // Economics (Social side)
    "Development Studies","African Studies","Asian Studies","Latin American Studies",
    "Middle Eastern Studies","Indigenous and Native Studies","Canadian Studies",
    "American Studies","European Studies","Gender Studies"
  ],
  "Science": [
    // Biology
    "Biology","General Biology","Marine Biology","Wildlife Biology",
    "Conservation Biology","Evolutionary Biology","Ecology","Plant Biology",
    "Botany","Zoology","Entomology","Ornithology","Ichthyology",
    "Cell Biology","Developmental Biology","Neuroscience","Neurobiology",
    // Chemistry
    "Chemistry","Analytical Chemistry","Organic Chemistry","Inorganic Chemistry",
    "Physical Chemistry","Environmental Chemistry","Medicinal Chemistry",
    "Computational Chemistry","Polymer Chemistry","Nuclear Chemistry",
    // Physics / Math
    "Physics","Applied Physics","Astrophysics","Astronomy","Cosmology",
    "Nuclear Physics","Particle Physics","Condensed Matter Physics",
    "Mathematical Physics","Geophysics","Optics",
    "Mathematics","Applied Mathematics","Pure Mathematics","Statistics",
    "Actuarial Mathematics","Financial Mathematics","Mathematical Finance",
    "Combinatorics and Optimization","Computational Mathematics",
    // Earth Science
    "Earth Sciences","Geology","Geochemistry","Hydrogeology","Mineralogy",
    "Paleontology","Glaciology","Climatology","Meteorology","Oceanography",
    "Environmental Science","Environmental Studies","Sustainability",
    "Climate Change Studies","Renewable Energy Studies",
    // Other Science
    "Biochemistry","Biophysics","Chemical Biology","Science","Honours Science",
    "Liberal Science","Cognitive Science","Forensic Science","Materials Science"
  ],
  "Education": [
    "Education","Elementary Education","Secondary Education","Early Childhood Education",
    "Child Development","Special Education","Inclusive Education","Gifted Education",
    "Indigenous Education","Bilingual Education","French Immersion Education",
    "Physical and Health Education","Technology Education","Arts Education",
    "Music Education","Drama Education","English Education","Mathematics Education",
    "Science Education","Social Studies Education","Adult Education",
    "Post-Secondary Education","Continuing Education","Vocational Education",
    "Educational Leadership","Curriculum and Instruction","Educational Psychology",
    "Educational Technology","E-Learning","Instructional Design","Coaching"
  ],
  "Law": [
    "Pre-Law","Law and Justice","Law and Society","Law and Business",
    "Law and Technology","Constitutional Law","Criminal Law","Family Law",
    "Immigration Law","International Law","Environmental Law","Tax Law",
    "Corporate Law","Labour Law","Property Law","Human Rights Law",
    "Indigenous Law","Privacy Law","Cybersecurity Law","Bioethics and Law"
  ],
  "Trades & Applied Technology": [
    "Architectural Technology","Building Design Technology","Construction Technology",
    "Civil Engineering Technology","Electrical Engineering Technology",
    "Mechanical Engineering Technology","Electronic Engineering Technology",
    "Computer Systems Technology","Networking Technology","Welding Engineering Technology",
    "Manufacturing Technology","Automation Technology","Quality Assurance Technology",
    "Instrumentation and Control Technology","Plumbing and Pipefitting Technology",
    "Aviation Technology","Marine Engineering Technology","Automotive Technology",
    "Diesel Technology","Heavy Equipment Technology"
  ],
  "Agriculture & Environment": [
    "Agriculture","Agricultural Science","Agribusiness","Agronomy",
    "Animal Science","Animal Husbandry","Aquaculture","Livestock Management",
    "Horticulture","Landscape Horticulture","Viticulture and Enology",
    "Sustainable Agriculture","Organic Agriculture","Food Systems",
    "Forestry","Forest Management","Forest Recreation","Wildlife Management",
    "Natural Resources","Natural Resources Management","Conservation",
    "Environmental Management","Environmental Monitoring","Water Quality",
    "Watershed Management","Land Use Planning","Agroecology",
    "Soil Science","Rangeland Management","Parks and Protected Areas"
  ],
  "Media & Communication": [
    "Communications","Communication Studies","Mass Communication","Strategic Communication",
    "Public Relations","Corporate Communications","Political Communication",
    "Health Communication","Science Communication","Digital Communication",
    "Multimedia","Digital Media","New Media","Social Media Management",
    "Broadcasting","Radio Broadcasting","Television Broadcasting","Podcasting",
    "Film Production","Screenwriting","Cinematography","Directing",
    "Documentary Filmmaking","Animation Production","Game Design",
    "UX Design","UI Design","Web Design","Interaction Design"
  ],
  "Architecture & Design": [
    "Architecture","Architectural Studies","Architectural Design","Landscape Architecture",
    "Urban Design","Interior Architecture","Environmental Design","Industrial Design",
    "Product Design","Furniture Design","Fashion Design","Textile Design",
    "Graphic Design","Visual Communication Design","Interaction Design",
    "Digital Design","Animation","Motion Graphics","Game Art","3D Modeling"
  ],
  "Social Work & Community": [
    "Social Work","Child and Youth Work","Community Development","Community Services",
    "Youth Justice","Addictions and Mental Health","Gerontology","Aging Studies",
    "Palliative Care","Chaplaincy","Indigenous Community Development",
    "Community Rehabilitation","Victim Services","Violence Prevention",
    "Family Support","Housing and Homelessness","Food Security Studies"
  ],
  "Kinesiology & Sport": [
    "Kinesiology","Exercise Science","Human Kinetics","Sport Science",
    "Sport and Exercise Psychology","Coaching","Athletic Therapy","Physical Education",
    "Recreation Administration","Outdoor Recreation","Adventure Tourism",
    "Sport Management","Sport Analytics","Performance Analysis","Biomechanics",
    "Motor Learning","Strength and Conditioning","Sport Nutrition"
  ]
};

// ───────────────────────────────────────────────────────────
//  UNIVERSITIES DATABASE  (Accurate 2024-2025 data)
// ───────────────────────────────────────────────────────────
const UNIVERSITIES = [
  {
    id: "uoft",
    name: "University of Toronto",
    shortName: "U of T",
    loc: "Toronto, Ontario",
    province: "Ontario",
    city: "Toronto",
    citySize: "big",
    lat: 43.6629, lng: -79.3957,
    canadaRank: 1, worldRank: 21,
    comp: "very",
    compLabel: "Very Competitive",
    avgRange: { low: 90, high: 97 },
    tuition: { domestic: 14834, intl: 58680 },
    coop: true, coopLabel: "Yes (varies by program)",
    campusSize: "Large (Urban)",
    vibe: "Academically intense, extremely diverse, urban campus. One of the world's top research universities. Best for students who thrive in large, competitive environments.",
    programs: ["Mechanical Engineering","Electrical Engineering","Computer Engineering","Chemical Engineering","Civil Engineering","Engineering Science (incl. Aerospace)","Industrial Engineering","Computer Science","Software Engineering","Data Science","Mathematics","Statistics","Business (Rotman)","Commerce","Economics","Medicine","Law","Architecture","Nursing","Pharmacy","Dentistry","Education","Social Work","Arts & Science","Psychology","Biochemistry","Physics","Biology","English","Political Science","History","Music"],
    scholarships: ["University of Toronto Excellence Award ($5,000–$7,500, automatic 95%+)","National Scholarship Program ($10,000+)","Lester B. Pearson International Scholarship (full tuition)"],
    applyURL: "https://www.ouac.on.ca",
    websiteURL: "https://www.utoronto.ca",
    deadlines: { main: "Feb 1", earlyConsideration: "Nov 1 (some programs)" },
    residence: { avg: 12500, notes: "Guaranteed first-year" },
    coopNote: "Co-op available in Engineering, CS, and some Science programs. PEY (Professional Experience Year) available for many programs.",
    repNote: "#1 in Canada, #21 globally (QS 2025). Strongest in Medicine, Law, Engineering, Economics.",
    gradRate: "93%",
    avgClassSize: "Large (200+ in first year for some programs)"
  },
  {
    id: "ubc",
    name: "University of British Columbia",
    shortName: "UBC",
    loc: "Vancouver, BC",
    province: "British Columbia",
    city: "Vancouver",
    citySize: "big",
    lat: 49.2606, lng: -123.2460,
    canadaRank: 2, worldRank: 34,
    comp: "very",
    compLabel: "Very Competitive",
    avgRange: { low: 87, high: 95 },
    tuition: { domestic: 5899, intl: 42603 },
    coop: true, coopLabel: "Yes (strong co-op)",
    campusSize: "Large (Point Grey campus, 400 ha)",
    vibe: "World-class campus surrounded by nature. Progressive, internationally diverse. Strong in research, sustainability, and arts. Beloved by students for campus life and Vancouver lifestyle.",
    programs: ["Mechanical Engineering","Electrical Engineering","Civil Engineering","Chemical & Biological Engineering","Computer Engineering","Computer Science","Software Engineering","Data Science","Business (Sauder)","Commerce","Economics","Forestry","Environmental Science","Land & Food Systems","Nursing","Medicine","Law","Architecture","Education","Music","Psychology","Biology","Chemistry","Physics","Political Science","Arts (General)","Social Work","Kinesiology"],
    scholarships: ["Trek Excellence Scholarship ($4,000, automatic for high averages)","International Major Entrance Scholarship (up to $80,000 over 4 years for intl)","President's Entrance Scholarship (varies)"],
    applyURL: "https://you.ubc.ca/applying-ubc/",
    websiteURL: "https://www.ubc.ca",
    deadlines: { main: "Jan 15" },
    residence: { avg: 10200, notes: "Guaranteed first-year (if applied by deadline)" },
    coopNote: "Co-op offered in Engineering, Sciences, Computer Science, Commerce, and Forestry. Competitive placement.",
    repNote: "#2 in Canada, #34 globally (QS 2025). Globally renowned for Forestry, Environmental Sciences, and Medicine.",
    gradRate: "90%"
  },
  {
    id: "mcgill",
    name: "McGill University",
    shortName: "McGill",
    loc: "Montréal, Québec",
    province: "Quebec",
    city: "Montréal",
    citySize: "big",
    lat: 45.5048, lng: -73.5772,
    canadaRank: 3, worldRank: 30,
    comp: "very",
    compLabel: "Very Competitive",
    avgRange: { low: 87, high: 95 },
    tuition: { domestic: 2869, intl: 22185 },
    coop: false, coopLabel: "Limited (select programs)",
    campusSize: "Mid-size (urban, downtown Montréal)",
    vibe: "Historic (founded 1821), bilingual city, amazing social scene. Affordable tuition. Extremely strong in Medicine, Law, and Sciences. High international reputation — known as the 'Harvard of Canada'.",
    programs: ["Mechanical Engineering","Civil Engineering","Electrical Engineering","Chemical Engineering","Computer Science","Software Engineering","Medicine","Law","Dentistry","Nursing","Management (Desautels)","Economics","Architecture","Music","Education","Social Work","Biology","Chemistry","Physics","Mathematics","Psychology","Political Science","History","Arts (General)","Biochemistry"],
    scholarships: ["Principal's Scholarships (up to $20,000, automatic)","Faculty Awards (varies)","In-Course Excellence Awards"],
    applyURL: "https://www.mcgill.ca/applying/",
    websiteURL: "https://www.mcgill.ca",
    deadlines: { main: "Jan 15" },
    residence: { avg: 11000, notes: "Competitive — apply early" },
    coopNote: "Co-op limited. Some internship programs available through faculties.",
    repNote: "#3 in Canada, #30 globally (QS 2025). World-renowned for Medicine, Law, and Natural Sciences.",
    gradRate: "91%"
  },
  {
    id: "waterloo",
    name: "University of Waterloo",
    shortName: "Waterloo",
    loc: "Waterloo, Ontario",
    province: "Ontario",
    city: "Waterloo",
    citySize: "mid",
    lat: 43.4723, lng: -80.5449,
    canadaRank: 7, worldRank: 154,
    comp: "very",
    compLabel: "Very Competitive",
    avgRange: { low: 90, high: 97 },
    tuition: { domestic: 14100, intl: 55000 },
    coop: true, coopLabel: "World's largest co-op program",
    campusSize: "Large (main campus + North campus)",
    vibe: "The co-op capital of Canada. Startup culture, strong tech industry connections, entrepreneurial energy. Best for STEM students who want real-world experience before graduating.",
    programs: ["Mechanical Engineering","Electrical Engineering","Computer Engineering","Civil Engineering","Chemical Engineering","Mechatronics Engineering","Systems Design Engineering","Environmental Engineering","Geological Engineering","Software Engineering","Computer Science","Mathematics","Statistics","Data Science","Actuarial Science","Accounting & Financial Management","Kinesiology","Health Sciences","Architecture","Environment & Resource Studies","Biology","Chemistry","Physics","Psychology","Economics","Arts (General)"],
    scholarships: ["President's Scholarship ($2,000, 95%+, automatic)","Engineering Excellence Award (varies)","Provost's Scholars Award ($2,500)"],
    applyURL: "https://www.ouac.on.ca",
    websiteURL: "https://uwaterloo.ca",
    deadlines: { main: "Feb 1", aif: "Feb 1 (AIF — mandatory for most programs)" },
    residence: { avg: 11000, notes: "Guaranteed first-year if applied early" },
    coopNote: "100% of Engineering and CS students participate in 6 co-op terms (~20 months of paid work). Average co-op salary $25,000–$40,000/yr by senior year.",
    repNote: "#7 in Canada, #154 globally. #1 in Canada for co-op, #1 for Computer Science employer connections. Produces more startup founders than any Canadian university.",
    gradRate: "87%"
  },
  {
    id: "mcmaster",
    name: "McMaster University",
    shortName: "McMaster",
    loc: "Hamilton, Ontario",
    province: "Ontario",
    city: "Hamilton",
    citySize: "mid",
    lat: 43.2609, lng: -79.9192,
    canadaRank: 5, worldRank: 189,
    comp: "comp",
    compLabel: "Competitive",
    avgRange: { low: 83, high: 93 },
    tuition: { domestic: 9660, intl: 35000 },
    coop: true, coopLabel: "Yes (Engineering, Business, Science)",
    campusSize: "Mid-size (suburban Hamilton)",
    vibe: "Collaborative, inquiry-based learning. World-famous problem-based Health Sciences program. Warm community feel. Beautiful campus. Close to Toronto (~45 min) without Toronto's cost.",
    programs: ["Health Sciences","Nursing","Midwifery","Kinesiology","Medical Radiation Sciences","Biochemistry","Chemical Engineering","Civil Engineering","Electrical Engineering","Mechanical Engineering","Software Engineering","Computer Science","Business (DeGroote)","Commerce","Economics","Biology","Chemistry","Physics","Psychology","Social Work","Arts & Science","Humanities","Sociology","Political Science"],
    scholarships: ["McMaster University Award of Excellence ($3,000–$5,000, automatic 90%+)","National Scholarship (up to $24,000)","Engineering Awards (varies)"],
    applyURL: "https://www.ouac.on.ca",
    websiteURL: "https://www.mcmaster.ca",
    deadlines: { main: "Feb 1" },
    residence: { avg: 10600, notes: "Strongly recommended first year — apply early" },
    coopNote: "Co-op available in Engineering, Business, and select Science programs. Placements in Hamilton, Toronto, and beyond.",
    repNote: "#5 in Canada, #189 globally. #1 in Canada for Health Sciences (problem-based learning model). Strong in Engineering and Business.",
    gradRate: "89%"
  },
  {
    id: "queens",
    name: "Queen's University",
    shortName: "Queen's",
    loc: "Kingston, Ontario",
    province: "Ontario",
    city: "Kingston",
    citySize: "mid",
    lat: 44.2253, lng: -76.4951,
    canadaRank: 6, worldRank: 209,
    comp: "comp",
    compLabel: "Competitive",
    avgRange: { low: 85, high: 93 },
    tuition: { domestic: 16046, intl: 51000 },
    coop: true, coopLabel: "Yes (Engineering, Science)",
    campusSize: "Mid-size (classic campus, Kingston)",
    vibe: "Legendary school spirit (Gaels!). Tight-knit community. Exceptional alumni network. Known for Smith Commerce, Engineering, and Law. Strong Greek life and clubs.",
    programs: ["Commerce (Smith School of Business)","Mechanical Engineering","Electrical Engineering","Civil Engineering","Chemical Engineering","Computer Engineering","Computing","Computer Science","Nursing","Life Sciences","Biochemistry","Rehabilitation Sciences","Law","Arts & Science","Biology","Chemistry","Physics","Psychology","Economics","Political Science","Education","Music","Mathematics"],
    scholarships: ["Principal's Scholarship ($8,000–$36,000)","Chancellor's Scholarship ($36,000, full tuition)","Smith Commerce Entrance Awards (varies)"],
    applyURL: "https://www.ouac.on.ca",
    websiteURL: "https://www.queensu.ca",
    deadlines: { main: "Feb 1" },
    residence: { avg: 12800, notes: "Guaranteed first-year" },
    coopNote: "Co-op available in Engineering and Applied Science. Smith Commerce offers internship term.",
    repNote: "#6 in Canada, #209 globally. Smith School of Business consistently ranked #1 in Canada for undergraduate business.",
    gradRate: "90%"
  },
  {
    id: "western",
    name: "Western University",
    shortName: "Western",
    loc: "London, Ontario",
    province: "Ontario",
    city: "London",
    citySize: "mid",
    lat: 43.0096, lng: -81.2737,
    canadaRank: 8, worldRank: 203,
    comp: "comp",
    compLabel: "Competitive",
    avgRange: { low: 83, high: 92 },
    tuition: { domestic: 10617, intl: 33000 },
    coop: true, coopLabel: "Yes (Engineering, Science, some Arts)",
    campusSize: "Large (beautiful riverside campus)",
    vibe: "Beautiful campus, vibrant social life, strong athletics. Known for Ivey Business School (apply in 2nd year), great campus experience, and strong alumni network.",
    programs: ["Mechanical Engineering","Electrical Engineering","Civil Engineering","Chemical Engineering","Integrated Engineering","Software Engineering","Computer Science","Medical Sciences","Health Sciences","Kinesiology","Nursing","Business (Ivey — 2nd year entry)","Law","Biology","Biochemistry","Chemistry","Physics","Mathematics","Psychology","Sociology","Political Science","Geography","Media","Music","Arts & Humanities","Education","Social Work"],
    scholarships: ["Western Scholarship of Distinction ($2,000, 90%+, automatic)","National Scholarship (up to $30,000)","Westerns Continuing Scholarships (renewable)"],
    applyURL: "https://www.ouac.on.ca",
    websiteURL: "https://www.uwo.ca",
    deadlines: { main: "Feb 1" },
    residence: { avg: 11500, notes: "Guaranteed first-year; great residence culture" },
    coopNote: "Co-op and internship programs in Engineering, Science, and select Faculties. Ivey HBA has industry placements.",
    repNote: "#8 in Canada, #203 globally. Ivey Business School ranked #1 for MBA in Canada. Strong in Law, Engineering, and Health Sciences.",
    gradRate: "91%"
  },
  {
    id: "alberta",
    name: "University of Alberta",
    shortName: "U of A",
    loc: "Edmonton, Alberta",
    province: "Alberta",
    city: "Edmonton",
    citySize: "big",
    lat: 53.5232, lng: -113.5263,
    canadaRank: 4, worldRank: 110,
    comp: "comp",
    compLabel: "Competitive",
    avgRange: { low: 80, high: 90 },
    tuition: { domestic: 6571, intl: 28000 },
    coop: true, coopLabel: "Yes",
    campusSize: "Large",
    vibe: "Major research university in Canada's energy capital. Tight community. Strong in Engineering, Law, and Sciences. More affordable than Ontario schools with comparable quality.",
    programs: ["Mechanical Engineering","Electrical Engineering","Civil Engineering","Chemical Engineering","Petroleum Engineering","Computer Engineering","Computing Science","Software Engineering","Business (Alberta School of Business)","Accounting","Finance","Economics","Medicine","Law","Dentistry","Pharmacy","Nursing","Kinesiology","Agriculture","Agricultural & Resource Economics","Biology","Chemistry","Physics","Psychology","Political Science","Education","Social Work","Arts (General)"],
    scholarships: ["University of Alberta Excellence Scholarships (various)","Alexander Rutherford Scholarship (Alberta govt, up to $2,500)","Jason Lang Scholarship ($1,000/yr, renewal)"],
    applyURL: "https://www.ualberta.ca/admissions/",
    websiteURL: "https://www.ualberta.ca",
    deadlines: { main: "Mar 1" },
    residence: { avg: 9500, notes: "Guaranteed first-year" },
    coopNote: "Co-op in Engineering, Computing Science, Business, and Science. Strong industry connections with Alberta energy sector.",
    repNote: "#4 in Canada, #110 globally (QS 2025). World-class in Energy Research, Petroleum Engineering, and Agricultural Sciences.",
    gradRate: "86%"
  },
  {
    id: "calgary",
    name: "University of Calgary",
    shortName: "UCalgary",
    loc: "Calgary, Alberta",
    province: "Alberta",
    city: "Calgary",
    citySize: "big",
    lat: 51.0768, lng: -114.1320,
    canadaRank: 9, worldRank: 182,
    comp: "comp",
    compLabel: "Competitive",
    avgRange: { low: 75, high: 87 },
    tuition: { domestic: 7050, intl: 25000 },
    coop: true, coopLabel: "Yes",
    campusSize: "Large",
    vibe: "Innovative and entrepreneurial. Canada's 'startup university'. Energy industry hub. Strong professional programs. Proximity to Rockies is a bonus.",
    programs: ["Mechanical Engineering","Electrical Engineering","Civil Engineering","Chemical Engineering","Computer Engineering","Software Engineering","Petroleum Engineering","Computer Science","Business (Haskayne)","Accounting","Finance","Economics","Medicine","Law","Nursing","Kinesiology","Environmental Design","Biology","Chemistry","Physics","Mathematics","Psychology","Social Work","Education","Political Science","Geography","Social Sciences"],
    scholarships: ["Schulich Leader Scholarship (STEM, $12,000–$20,000)","Academic Excellence Award (automatic, varies)","Eyes High Entrance Scholarship"],
    applyURL: "https://www.ucalgary.ca/future-students/undergraduate/apply",
    websiteURL: "https://www.ucalgary.ca",
    deadlines: { main: "Mar 1" },
    residence: { avg: 9000, notes: "Available first year" },
    coopNote: "Co-op available in Engineering, Science, and Haskayne Business School.",
    repNote: "#9 in Canada, #182 globally. Strong in Energy, Medicine (problem-based program modeled on McMaster), and Business.",
    gradRate: "84%"
  },
  {
    id: "sfu",
    name: "Simon Fraser University",
    shortName: "SFU",
    loc: "Burnaby, BC",
    province: "British Columbia",
    city: "Vancouver",
    citySize: "big",
    lat: 49.2790, lng: -122.9195,
    canadaRank: 11, worldRank: 298,
    comp: "comp",
    compLabel: "Competitive",
    avgRange: { low: 78, high: 88 },
    tuition: { domestic: 7354, intl: 26000 },
    coop: true, coopLabel: "Excellent co-op program",
    campusSize: "Mid-size (hilltop + downtown Burnaby)",
    vibe: "Second largest in BC. Excellent co-op. Strong in CS, Business, and Communication. Mountainside campus with stunning views. Downtown Vancouver campus as well.",
    programs: ["Computing Science","Software Engineering","Mechatronic Systems Engineering","Computer Engineering","Engineering Science","Business (Beedie)","Accounting","Finance","Economics","Health Sciences","Kinesiology","Criminology","Communication","Interactive Arts","Interactive Systems","Psychology","Biology","Chemistry","Physics","Environmental Science","Education","Political Science","Sociology","Arts (General)"],
    scholarships: ["SFU Undergraduate Open Scholarship (varies)","Major Entrance Scholarship ($3,500–$5,000)","Dual Credit Awards"],
    applyURL: "https://www.sfu.ca/students/apply.html",
    websiteURL: "https://www.sfu.ca",
    deadlines: { main: "Feb 1 (Spring), May 1 (Fall)" },
    residence: { avg: 9500, notes: "Available — apply early" },
    coopNote: "SFU has one of Canada's strongest co-op programs, especially in CS, Engineering, and Business. 3,000+ co-op positions annually.",
    repNote: "#11 in Canada. Recognized globally for its co-op program and Computing Science strength.",
    gradRate: "82%"
  },
  {
    id: "dalhousie",
    name: "Dalhousie University",
    shortName: "Dal",
    loc: "Halifax, Nova Scotia",
    province: "Nova Scotia",
    city: "Halifax",
    citySize: "mid",
    lat: 44.6369, lng: -63.5917,
    canadaRank: 13, worldRank: 298,
    comp: "mod",
    compLabel: "Moderate",
    avgRange: { low: 74, high: 85 },
    tuition: { domestic: 10262, intl: 23000 },
    coop: true, coopLabel: "Yes",
    campusSize: "Mid-size (Halifax, NS)",
    vibe: "Best East Coast university experience. Halifax is vibrant and affordable. Known for Law, Medicine, Marine Biology, and Ocean Sciences. Welcoming, outdoorsy community.",
    programs: ["Mechanical Engineering","Electrical Engineering","Civil Engineering","Chemical Engineering","Ocean & Naval Architecture","Computer Science","Computer Engineering","Commerce","Business","Economics","Medicine","Law","Dentistry","Nursing","Pharmacy","Health Sciences","Architecture","Community Design","Planning","Agriculture","Environmental Science","Oceanography","Marine Biology","Biology","Chemistry","Physics","Psychology","Social Work","Arts & Social Sciences","Political Science","History"],
    scholarships: ["Dalhousie Excellence Award ($4,000, automatic 95%+)","Sexton Scholarship (Engineering, $10,000)","Killam Scholarship (varies)","Nova Scotia Bursary"],
    applyURL: "https://www.dal.ca/admissions/",
    websiteURL: "https://www.dal.ca",
    deadlines: { main: "Mar 1" },
    residence: { avg: 10000, notes: "Guaranteed first-year (Howe Hall, Shirreff Hall, etc.)" },
    coopNote: "Co-op in Engineering, Computing Science, Commerce, and Science. Strong maritime industry connections.",
    repNote: "#13 in Canada. Best East Coast university. World-renowned Ocean Sciences program. Strong Law and Medicine.",
    gradRate: "83%"
  },
  {
    id: "uottawa",
    name: "University of Ottawa",
    shortName: "uOttawa",
    loc: "Ottawa, Ontario",
    province: "Ontario",
    city: "Ottawa",
    citySize: "big",
    lat: 45.4231, lng: -75.6831,
    canadaRank: 10, worldRank: 203,
    comp: "mod",
    compLabel: "Moderate",
    avgRange: { low: 74, high: 87 },
    tuition: { domestic: 8360, intl: 30000 },
    coop: true, coopLabel: "Yes",
    campusSize: "Mid-size (bilingual, downtown Ottawa)",
    vibe: "Canada's bilingual university in the nation's capital. Government connections, excellent Law and Social Sciences. Two official languages means double the career doors.",
    programs: ["Mechanical Engineering","Electrical Engineering","Civil Engineering","Chemical Engineering","Computer Engineering","Software Engineering","Computer Science","Data Science","Business (Telfer)","Accounting","Finance","Economics","Medicine","Law (Civil Law)","Law (Common Law)","Nursing","Health Sciences","Communication","Psychology","Biology","Chemistry","Physics","Mathematics","Political Science","Sociology","Social Work","Education","Arts (General)"],
    scholarships: ["Admission Scholarships ($1,000–$4,000, automatic)","Excellence Scholarship (90%+, $2,000–$4,000)","Bilingualism Bursary"],
    applyURL: "https://www.ouac.on.ca",
    websiteURL: "https://www.uottawa.ca",
    deadlines: { main: "Apr 1 (some programs Feb 1)" },
    residence: { avg: 10200, notes: "Guaranteed first-year (applied on time)" },
    coopNote: "One of Canada's largest co-op programs — 9,000+ students, 5,000+ employers.",
    repNote: "#10 in Canada, bilingual institution. Strong in Law (one of Canada's best), Government Relations, and Bilingual Programs.",
    gradRate: "85%"
  },
  {
    id: "tmu",
    name: "Toronto Metropolitan University",
    shortName: "TMU",
    loc: "Toronto, Ontario",
    province: "Ontario",
    city: "Toronto",
    citySize: "big",
    lat: 43.6577, lng: -79.3788,
    canadaRank: 16, worldRank: null,
    comp: "mod",
    compLabel: "Moderate",
    avgRange: { low: 75, high: 88 },
    tuition: { domestic: 9300, intl: 32000 },
    coop: true, coopLabel: "Yes",
    campusSize: "Urban (downtown Toronto)",
    vibe: "Career-focused, urban, diverse. Strong in Engineering, Business, Media, and Design. Heart of Toronto — real city experience. Great for students who want industry connections from day one.",
    programs: ["Mechanical Engineering","Electrical Engineering","Civil Engineering","Chemical Engineering","Computer Engineering","Aerospace Engineering","Business (Ted Rogers)","Accounting","Finance","Marketing","Economics","Computer Science","Data Science","Nursing","Midwifery","Architecture","Interior Design","Fashion","Communication","Media Production","Graphic Communications","Creative Industries","Social Work","Legal Studies","Biology","Chemistry","Physics","Psychology"],
    scholarships: ["TMU Entrance Scholarship ($1,000–$4,000)","Juma Al-JouJou Awards (varies)","Community Engagement Awards"],
    applyURL: "https://www.ouac.on.ca",
    websiteURL: "https://www.torontomu.ca",
    deadlines: { main: "Feb 1" },
    residence: { avg: 13500, notes: "Downtown — limited on-campus; most students live nearby" },
    coopNote: "Co-op available in Engineering, Computing, Business, and Communication programs.",
    repNote: "Top career-focused university in Toronto. Known for Ted Rogers Business School and strong industry placements.",
    gradRate: "80%"
  },
  {
    id: "york",
    name: "York University",
    shortName: "York",
    loc: "Toronto, Ontario",
    province: "Ontario",
    city: "Toronto",
    citySize: "big",
    lat: 43.7735, lng: -79.5019,
    canadaRank: 14, worldRank: 401,
    comp: "mod",
    compLabel: "Moderate",
    avgRange: { low: 73, high: 84 },
    tuition: { domestic: 8400, intl: 30000 },
    coop: true, coopLabel: "Yes (Schulich, Lassonde)",
    campusSize: "Large (Keele campus + Glendon)",
    vibe: "Diverse and large. Known for Schulich Business (top MBA in Canada), Osgoode Law (top 3 in Canada), and Lassonde Engineering. Glendon campus is bilingual.",
    programs: ["Business (Schulich)","Accounting","Finance","Marketing","Law (Osgoode)","Mechanical Engineering (Lassonde)","Electrical Engineering (Lassonde)","Computer Engineering (Lassonde)","Software Engineering (Lassonde)","Computer Science","Data Science","Kinesiology","Nursing","Health","Fine Arts","Film","Theatre","Education","Environmental Studies","Social Work","Liberal Arts","Political Science","Psychology","Sociology","Biology","Chemistry","Physics","Mathematics"],
    scholarships: ["Schulich Leader Scholarship (STEM, $12,000)","President's Scholarship (up to $36,000)","York University International Awards"],
    applyURL: "https://www.ouac.on.ca",
    websiteURL: "https://www.yorku.ca",
    deadlines: { main: "Feb 1" },
    residence: { avg: 12000, notes: "Available; apply early" },
    coopNote: "Co-op and work-integrated learning in Schulich, Lassonde, and select programs.",
    repNote: "#14 in Canada. Schulich School of Business and Osgoode Hall Law School are world-renowned. Lassonde engineering growing rapidly.",
    gradRate: "79%"
  },
  {
    id: "umanitoba",
    name: "University of Manitoba",
    shortName: "U of M",
    loc: "Winnipeg, Manitoba",
    province: "Manitoba",
    city: "Winnipeg",
    citySize: "mid",
    lat: 49.8076, lng: -97.1348,
    canadaRank: 15, worldRank: 501,
    comp: "mod",
    compLabel: "Moderate",
    avgRange: { low: 70, high: 82 },
    tuition: { domestic: 5200, intl: 18000 },
    coop: true, coopLabel: "Yes",
    campusSize: "Large",
    vibe: "Affordable, strong research tradition. Best in Manitoba for Medicine, Engineering, and Agriculture. Safe, community-oriented campus. Friendly city.",
    programs: ["Mechanical Engineering","Electrical Engineering","Civil Engineering","Chemical Engineering","Agricultural & Biosystems Engineering","Computer Engineering","Computer Science","Business","Accounting","Finance","Medicine","Law","Dentistry","Pharmacy","Nursing","Kinesiology","Agriculture","Agribusiness","Food Science","Biology","Chemistry","Physics","Mathematics","Psychology","Social Work","Education","Arts (General)","Political Science","Economics"],
    scholarships: ["Scholarship of Distinction (automatic, various amounts)","Manitoba Student Aid","University of Manitoba Graduate Fellowship"],
    applyURL: "https://umanitoba.ca/admissions/",
    websiteURL: "https://umanitoba.ca",
    deadlines: { main: "May 1 (most programs)" },
    residence: { avg: 8500, notes: "Available first year" },
    coopNote: "Co-op in Engineering, Science, Business, and Computer Science.",
    repNote: "#15 in Canada. Strong Medicine and Agriculture faculties. Most affordable major research university in Canada.",
    gradRate: "80%"
  },
  {
    id: "usask",
    name: "University of Saskatchewan",
    shortName: "USask",
    loc: "Saskatoon, Saskatchewan",
    province: "Saskatchewan",
    city: "Saskatoon",
    citySize: "mid",
    lat: 52.1332, lng: -106.6310,
    canadaRank: 17, worldRank: 521,
    comp: "mod",
    compLabel: "Moderate",
    avgRange: { low: 70, high: 82 },
    tuition: { domestic: 5400, intl: 20000 },
    coop: true, coopLabel: "Yes",
    campusSize: "Large",
    vibe: "Canada's best for Veterinary Medicine and Agriculture. Tight-knit, safe community. Strong Indigenous research. Beautiful riverside campus.",
    programs: ["Agriculture","Agricultural Biology","Agribusiness","Veterinary Medicine","Animal Science","Mechanical Engineering","Civil Engineering","Chemical Engineering","Computer Science","Computer Engineering","Commerce","Accounting","Finance","Medicine","Law","Pharmacy","Nursing","Kinesiology","Nutrition & Dietetics","Biology","Chemistry","Physics","Mathematics","Psychology","Education","Social Work","Arts & Science","Environmental Science"],
    scholarships: ["University of Saskatchewan Entrance Scholarship (varies)","Indigenous Entrance Award","Saskatchewan Student Scholarships"],
    applyURL: "https://admissions.usask.ca/",
    websiteURL: "https://www.usask.ca",
    deadlines: { main: "Mar 1" },
    residence: { avg: 8000, notes: "Guaranteed first-year" },
    coopNote: "Co-op in Engineering, Computing, Commerce, and Agriculture.",
    repNote: "#17 in Canada. #1 in Canada for Veterinary Medicine (WCVM). World-class in Agriculture and Indigenous research.",
    gradRate: "82%"
  },
  {
    id: "unb",
    name: "University of New Brunswick",
    shortName: "UNB",
    loc: "Fredericton, New Brunswick",
    province: "New Brunswick",
    city: "Fredericton",
    citySize: "small",
    lat: 45.9636, lng: -66.6431,
    canadaRank: 19, worldRank: null,
    comp: "mod",
    compLabel: "Moderate",
    avgRange: { low: 68, high: 80 },
    tuition: { domestic: 9100, intl: 19000 },
    coop: true, coopLabel: "Yes",
    campusSize: "Mid-size",
    vibe: "Canada's oldest English-language university (1785). Strong Engineering and Forestry. Small city feel, close community. Good for students wanting a quieter, focused university experience.",
    programs: ["Mechanical Engineering","Electrical Engineering","Civil Engineering","Chemical Engineering","Computer Engineering","Software Engineering","Forestry & Environmental Management","Computer Science","Business","Accounting","Finance","Law","Nursing","Kinesiology","Biology","Chemistry","Physics","Mathematics","Psychology","Education","Social Work","Arts (General)","Political Science","Renaissance College (Leadership)"],
    scholarships: ["UNB Academic Excellence Award (automatic)","Atlantic Provinces Scholarship","Engineering Excellence Awards"],
    applyURL: "https://www.unb.ca/admissions/",
    websiteURL: "https://www.unb.ca",
    deadlines: { main: "Mar 31" },
    residence: { avg: 9000, notes: "Guaranteed first-year" },
    coopNote: "Co-op in Engineering, Science, Business, and Computer Science.",
    repNote: "#19 in Canada. Oldest English-language university. Excellent Engineering and Forestry programs.",
    gradRate: "78%"
  },
  {
    id: "mun",
    name: "Memorial University of Newfoundland",
    shortName: "MUN",
    loc: "St. John's, Newfoundland",
    province: "Newfoundland",
    city: "St. John's",
    citySize: "mid",
    lat: 47.5727, lng: -52.7339,
    canadaRank: 20, worldRank: 801,
    comp: "mod",
    compLabel: "Moderate",
    avgRange: { low: 67, high: 78 },
    tuition: { domestic: 2950, intl: 11460 },
    coop: true, coopLabel: "Yes",
    campusSize: "Mid-size",
    vibe: "Most affordable university in Canada. Welcoming, maritime culture. World-class Ocean Sciences and Marine Engineering. Great for students wanting low debt and a warm community.",
    programs: ["Mechanical Engineering","Electrical Engineering","Civil Engineering","Ocean & Naval Architectural Engineering","Computer Engineering","Computer Science","Business","Accounting","Finance","Medicine","Pharmacy","Nursing","Kinesiology","Ocean Sciences","Marine Biology","Environmental Science","Biology","Chemistry","Physics","Mathematics","Psychology","Music","Social Work","Education","Arts (General)"],
    scholarships: ["MUN Entrance Scholarship (automatic)","Ocean Sciences Awards","Newfoundland & Labrador Provincial Bursary"],
    applyURL: "https://www.mun.ca/undergrad/",
    websiteURL: "https://www.mun.ca",
    deadlines: { main: "Mar 1" },
    residence: { avg: 7500, notes: "Available; very affordable" },
    coopNote: "Co-op in Engineering, Computing, Business, and Sciences.",
    repNote: "Most affordable tuition in Canada. World-renowned for Ocean and Marine Sciences.",
    gradRate: "77%"
  },
  {
    id: "concordia",
    name: "Concordia University",
    shortName: "Concordia",
    loc: "Montréal, Québec",
    province: "Quebec",
    city: "Montréal",
    citySize: "big",
    lat: 45.4949, lng: -73.5779,
    canadaRank: 18, worldRank: 801,
    comp: "mod",
    compLabel: "Moderate",
    avgRange: { low: 70, high: 82 },
    tuition: { domestic: 3700, intl: 18000 },
    coop: false, coopLabel: "Limited",
    campusSize: "Urban (two Montréal campuses)",
    vibe: "Creative, urban, and diverse. Known for Fine Arts (one of North America's best), John Molson Business School, and Film/Communication. Very affordable in Montréal.",
    programs: ["Fine Arts","Studio Arts","Art History","Film Studies","Creative Arts Therapies","Theatre","Music","Mechanical Engineering","Electrical Engineering","Civil Engineering","Software Engineering","Computer Science","Business (John Molson)","Accountancy","Finance","Marketing","Communication","Journalism","Journalism & Creative Writing","Psychology","Sociology","Education","Arts & Science","Biology","Chemistry","Political Science"],
    scholarships: ["Concordia Entrance Scholarship ($1,000–$5,000)","Fine Arts Awards","Concordia Merit Scholarship"],
    applyURL: "https://www.concordia.ca/admissions/",
    websiteURL: "https://www.concordia.ca",
    deadlines: { main: "Mar 1" },
    residence: { avg: 9500, notes: "Available — apply early" },
    coopNote: "Internship programs available through John Molson and Engineering.",
    repNote: "#18 in Canada. Best Fine Arts school in Quebec. John Molson Business School is highly regarded. Strong Film and Media programs.",
    gradRate: "76%"
  }
];

// ───────────────────────────────────────────────────────────
//  GRADE 12 ONTARIO COURSES (4U/4M) — 80+ courses
// ───────────────────────────────────────────────────────────
const GRADE12_COURSES = [
  // Mathematics
  { code: "MHF4U", name: "Advanced Functions", cat: "Mathematics" },
  { code: "MCV4U", name: "Calculus and Vectors", cat: "Mathematics" },
  { code: "MDM4U", name: "Mathematics of Data Management", cat: "Mathematics" },
  { code: "MAP4C", name: "Foundations for College Mathematics", cat: "Mathematics" },
  { code: "MEL4E", name: "Mathematics for Work and Everyday Life", cat: "Mathematics" },
  // Science
  { code: "SPH4U", name: "Physics", cat: "Science" },
  { code: "SCH4U", name: "Chemistry", cat: "Science" },
  { code: "SBI4U", name: "Biology", cat: "Science" },
  { code: "SES4U", name: "Earth and Space Science", cat: "Science" },
  { code: "SVN4M", name: "Environmental Science", cat: "Science" },
  { code: "SNC4M", name: "Science", cat: "Science" },
  // English
  { code: "ENG4U", name: "English", cat: "English" },
  { code: "EWC4U", name: "The Writer's Craft", cat: "English" },
  { code: "ETS4U", name: "Studies in Literature", cat: "English" },
  { code: "EAE4U", name: "English for Academic and Career Purposes", cat: "English" },
  { code: "ENG4E", name: "English for Everyday Life", cat: "English" },
  // French / Languages
  { code: "FIF4U", name: "French as a First Language", cat: "Languages" },
  { code: "FEF4U", name: "French as a Second Language (Immersion)", cat: "Languages" },
  { code: "FSF4U", name: "Core French", cat: "Languages" },
  { code: "LKBDU", name: "International Languages (varies)", cat: "Languages" },
  { code: "ESL4E", name: "English Literacy Development", cat: "Languages" },
  // Social Sciences & Humanities
  { code: "HSB4U", name: "Challenge and Change in Society", cat: "Social Sciences" },
  { code: "HHG4M", name: "Human Development Throughout the Lifespan", cat: "Social Sciences" },
  { code: "HFA4U", name: "Food and Culture", cat: "Social Sciences" },
  { code: "HRT4M", name: "World Religions and Belief Traditions", cat: "Social Sciences" },
  { code: "HPC4M", name: "Raising Healthy Children", cat: "Social Sciences" },
  { code: "HSE4M", name: "Equity and Social Justice", cat: "Social Sciences" },
  // Humanities
  { code: "HZT4U", name: "Philosophy: Questions and Theories", cat: "Humanities" },
  { code: "HZB4M", name: "Philosophy: The Big Questions", cat: "Humanities" },
  { code: "BOH4M", name: "Business Leadership", cat: "Business" },
  { code: "BAF3M", name: "Financial Accounting Fundamentals", cat: "Business" },
  { code: "BAT4M", name: "Financial Accounting Principles", cat: "Business" },
  { code: "BBB4M", name: "International Business Fundamentals", cat: "Business" },
  { code: "BDI4C", name: "Entrepreneurship: The Venture", cat: "Business" },
  { code: "BIM4C", name: "Marketing Fundamentals", cat: "Business" },
  { code: "BTA4O", name: "Information and Communication Technology", cat: "Business" },
  { code: "BTT1O", name: "Information and Communication Technology in Business", cat: "Business" },
  // History / Geography / Politics
  { code: "CHY4U", name: "World History Since the Fifteenth Century", cat: "History & Geography" },
  { code: "CHW3M", name: "World History to the End of the Fifteenth Century", cat: "History & Geography" },
  { code: "CHA4U", name: "Canada: History, Identity, and Culture", cat: "History & Geography" },
  { code: "CGW4U", name: "World Issues: A Geographic Analysis", cat: "History & Geography" },
  { code: "CGR4M", name: "Travel and Tourism: A Geographic Perspective", cat: "History & Geography" },
  { code: "CPC4E", name: "Civics and Citizenship", cat: "History & Geography" },
  { code: "CLN4U", name: "Canadian and International Law", cat: "History & Geography" },
  { code: "CPW4U", name: "Canadian and World Politics", cat: "History & Geography" },
  { code: "CIE4U", name: "The Individual and the Economy", cat: "History & Geography" },
  { code: "CIA4U", name: "Analysing Current Economic Issues", cat: "History & Geography" },
  // Arts
  { code: "AVI4M", name: "Visual Arts", cat: "Arts" },
  { code: "AWA4M", name: "Vocal Music", cat: "Arts" },
  { code: "AMU4M", name: "Instrumental Music", cat: "Arts" },
  { code: "ADA4M", name: "Dance", cat: "Arts" },
  { code: "ASM4M", name: "Media Arts", cat: "Arts" },
  { code: "ATC4M", name: "Technological Design", cat: "Arts" },
  { code: "ATD4M", name: "Photography", cat: "Arts" },
  { code: "AVI4E", name: "Visual Arts (Workplace)", cat: "Arts" },
  { code: "AWL4M", name: "Dramatic Arts", cat: "Arts" },
  // Technological Education
  { code: "TEJ4M", name: "Computer Engineering Technology", cat: "Technology" },
  { code: "TMJ4M", name: "Manufacturing Engineering Technology", cat: "Technology" },
  { code: "TCJ4C", name: "Construction Technology", cat: "Technology" },
  { code: "TTJ4C", name: "Transportation Technology", cat: "Technology" },
  { code: "TPJ4C", name: "Health Care", cat: "Technology" },
  { code: "TDJ4M", name: "Technological Design", cat: "Technology" },
  { code: "TGJ4M", name: "Communications Technology", cat: "Technology" },
  { code: "THJ4C", name: "Hospitality and Tourism", cat: "Technology" },
  // Computer Science
  { code: "ICS4U", name: "Computer Science", cat: "Computer Science" },
  { code: "ICS4C", name: "Introduction to Computer Studies", cat: "Computer Science" },
  { code: "IDC4O", name: "Interdisciplinary Studies — Computing", cat: "Computer Science" },
  // Physical Education & Health
  { code: "PPL4O", name: "Healthy Active Living Education", cat: "Phys Ed & Health" },
  { code: "PSK4U", name: "Introductory Kinesiology", cat: "Phys Ed & Health" },
  { code: "PAF4O", name: "Fitness and Lifestyle Management", cat: "Phys Ed & Health" },
  { code: "PAD4O", name: "Dance — Introductory", cat: "Phys Ed & Health" },
  // Co-op / Interdisciplinary
  { code: "GLE4O", name: "Learning Strategies", cat: "Other" },
  { code: "IDC4U", name: "Interdisciplinary Studies (University)", cat: "Other" },
  { code: "IDC4M", name: "Interdisciplinary Studies (Mixed)", cat: "Other" },
  { code: "ICE4M", name: "Co-operative Education", cat: "Other" },
  { code: "GPC4O", name: "Career Planning", cat: "Other" },
  { code: "MHF4U", name: "Advanced Functions (repeat for emphasis)", cat: "Mathematics" },
  { code: "NBE4U", name: "New Media Arts", cat: "Arts" },
  { code: "OLC4O", name: "Ontario Secondary School Literacy Course", cat: "Other" }
];

// ───────────────────────────────────────────────────────────
//  PROGRAM-SPECIFIC DATA  (what to show on saved.html)
// ───────────────────────────────────────────────────────────
const PROGRAM_DATA = {
  // key format: "universityId__programSlug"
  "waterloo__mechanical-engineering": {
    degreeType: "BASc — Bachelor of Applied Science",
    length: "5 years (co-op) / 4 years (no co-op)",
    coopTerms: 6,
    targetAvg: { low: 90, high: 94 },
    deadline: "Feb 1",
    earlyDeadline: "Nov 1 (some scholarship consideration)",
    tuition: 14100,
    competitiveness: "very",
    requiredCourses: ["MHF4U","MCV4U","SPH4U","SCH4U","ENG4U"],
    optionalCourse: true,
    aifRequired: true,
    aifURL: "https://uwaterloo.ca/future-students/applying/aif",
    applyURL: "https://www.ouac.on.ca",
    ecHighlights: ["Robotics Club (VEX, FIRST)","Hackathons (Hack the North)","Waterloo Math Contest","Engineering design teams","Research projects with professors","Student design competitions (SAE, Solar Car)"],
    scholarships: ["President's Scholarship ($2,000 – automatic 95%+)","Engineering Excellence Award (varies)","Waterloo Co-operative Education Award"],
    notes: "The AIF (Admission Information Form) is MANDATORY for all Engineering applicants and is heavily weighted alongside your grades."
  },
  "waterloo__computer-science": {
    degreeType: "BMath — Bachelor of Mathematics",
    length: "5 years (co-op) / 4 years (regular)",
    coopTerms: 5,
    targetAvg: { low: 93, high: 97 },
    deadline: "Feb 1",
    tuition: 14100,
    competitiveness: "very",
    requiredCourses: ["MHF4U","MCV4U","ICS4U","ENG4U"],
    optionalCourse: true,
    aifRequired: true,
    aifURL: "https://uwaterloo.ca/future-students/applying/aif",
    applyURL: "https://www.ouac.on.ca",
    ecHighlights: ["Canadian Computing Competition (CCC)","Competitive programming (LeetCode, Codeforces)","Hackathons","Open-source GitHub contributions","Math competitions (Euclid, AMC)","Personal programming projects"],
    scholarships: ["President's Scholarship ($2,000 – automatic 95%+)","Math Entrance Award (varies)","Computing Innovation Award"],
    notes: "Most competitive CS program in Canada. Average entry student has 94–97% with a strong AIF and coding portfolio."
  },
  "mcmaster__health-sciences": {
    degreeType: "BHSc — Bachelor of Health Sciences",
    length: "4 years",
    coopTerms: 0,
    targetAvg: { low: 92, high: 97 },
    deadline: "Feb 1",
    tuition: 9660,
    competitiveness: "very",
    requiredCourses: ["SBI4U","SCH4U","ENG4U","MHF4U"],
    optionalCourse: true,
    aifRequired: false,
    applyURL: "https://www.ouac.on.ca",
    ecHighlights: ["Hospital volunteering (200+ hours)","Research assistant positions","Health-related clubs","Community health initiatives","First aid/CPR certification","Science Olympics or health competitions"],
    scholarships: ["McMaster University Award of Excellence ($3,000–$5,000, automatic 90%+)","National Scholarship (up to $24,000)","Health Sciences Alumni Award"],
    notes: "Acceptance rate ~5% despite very high grades. The program uses Problem-Based Learning (PBL) and heavily weighs interview performance (OMSAS or internal). Community impact matters as much as GPA."
  },
  "mcmaster__engineering": {
    degreeType: "BEng — Bachelor of Engineering",
    length: "4–5 years",
    coopTerms: 3,
    targetAvg: { low: 85, high: 93 },
    deadline: "Feb 1",
    tuition: 9660,
    competitiveness: "comp",
    requiredCourses: ["MHF4U","MCV4U","SPH4U","SCH4U","ENG4U"],
    optionalCourse: true,
    aifRequired: false,
    applyURL: "https://www.ouac.on.ca",
    ecHighlights: ["Engineering clubs","Robotics teams","Math competitions","Design challenges","Coding projects","Volunteering in STEM education"],
    scholarships: ["McMaster University Award of Excellence","Engineering Excellence Award","Ontario Engineering Scholarships"],
    notes: "McMaster Engineering I is a common first year — you choose your specific discipline (Mechanical, Electrical, Chemical, etc.) after first year based on your grades and preferences."
  },
  "queens__commerce": {
    degreeType: "BCom — Bachelor of Commerce (Smith)",
    length: "4 years",
    coopTerms: 0,
    targetAvg: { low: 87, high: 94 },
    deadline: "Feb 1",
    tuition: 16046,
    competitiveness: "comp",
    requiredCourses: ["ENG4U","MHF4U"],
    optionalCourse: true,
    aifRequired: false,
    applyURL: "https://www.ouac.on.ca",
    ecHighlights: ["Student investment clubs","Case competition teams","Entrepreneurship clubs","Leadership roles (council, head of committees)","Community volunteering with quantifiable impact","Sports teams (competitive varsity or club)"],
    scholarships: ["Principal's Scholarship ($8,000–$36,000)","Chancellor's Scholarship (full tuition)","Smith Commerce Alumni Awards"],
    notes: "Smith Commerce at Queen's is ranked #1 in Canada for undergrad business. Strong emphasis on leadership, community, and extracurriculars — not just grades."
  },
  "uoft__engineering": {
    degreeType: "BASc — Bachelor of Applied Science",
    length: "4 years",
    coopTerms: 0,
    targetAvg: { low: 92, high: 97 },
    deadline: "Feb 1",
    tuition: 14834,
    competitiveness: "very",
    requiredCourses: ["MHF4U","MCV4U","SPH4U","SCH4U","ENG4U"],
    optionalCourse: true,
    aifRequired: false,
    applyURL: "https://www.ouac.on.ca",
    ecHighlights: ["Research with U of T professors (NSERC)","FIRST Robotics","Engineering competitions","Math/Physics Olympiads","Hackathons (UofTHacks)","Coding projects and GitHub"],
    scholarships: ["University of Toronto Excellence Award ($5,000–$7,500)","National Scholarship Program ($10,000+)","Engineering Faculty Awards"],
    notes: "U of T Engineering is extremely competitive and academically rigorous. PEY (16-month Professional Experience Year) available in 3rd year for co-op experience."
  },
  "ubc__science": {
    degreeType: "BSc — Bachelor of Science",
    length: "4 years",
    coopTerms: 4,
    targetAvg: { low: 85, high: 93 },
    deadline: "Jan 15",
    tuition: 5899,
    competitiveness: "very",
    requiredCourses: ["SBI4U","SCH4U","SPH4U","MHF4U","ENG4U"],
    optionalCourse: true,
    aifRequired: false,
    applyURL: "https://you.ubc.ca/applying-ubc/",
    ecHighlights: ["Science fairs","Research internships (NSERC USRA)","Biology/Chemistry clubs","Environmental volunteering","Science competitions","Lab volunteer work"],
    scholarships: ["Trek Excellence Scholarship ($4,000)","President's Entrance Scholarship","Science Faculty Awards"],
    notes: "UBC Science has one of Canada's strongest co-op programs with placements at top research institutes and biotech companies."
  }
};

// ───────────────────────────────────────────────────────────
//  SCHOLARSHIPS DATABASE  (representative 50, expandable)
// ───────────────────────────────────────────────────────────
const SCHOLARSHIPS = [
  // ── NATIONAL PRESTIGE ──
  { name:"Loran Award", amount:"$100,000 total ($25,000/yr × 4)", type:"merit", area:"any", prov:"National", desc:"Canada's most prestigious undergraduate scholarship. Awarded to students who demonstrate character, service, and leadership. Includes mentoring, travel grants, and summer leadership programs.", deadline:"Mid-November (school nomination)", link:"https://loranscholar.ca/", tags:["Merit","Leadership","National","Mentorship","Full Package"] },
  { name:"Schulich Leader Scholarship — Engineering/Science", amount:"$12,000 (STEM) / $20,000 (Computer Science)", type:"stem", area:"eng", prov:"National", desc:"For STEM-focused students entering university with demonstrated entrepreneurial leadership. Nominated through your high school. Over 100 awarded annually.", deadline:"Varies by school (March nomination)", link:"https://schulichleaders.com/", tags:["STEM","Leadership","Engineering","CS","Science"] },
  { name:"Terry Fox Humanitarian Award", amount:"$28,000 ($7,000/yr × 4)", type:"community", area:"any", prov:"National", desc:"For students who emulate Terry Fox's dedication to helping others — outstanding community service, leadership, courage and excellence in academics.", deadline:"February 1", link:"https://terryfox.org/humanitarian-award/", tags:["Community","Leadership","National","Humanitarian"] },
  { name:"RBC Future Launch Scholarship", amount:"$5,000", type:"merit", area:"any", prov:"National", desc:"Supporting young Canadians in building skills and accessing post-secondary education. Apply online with a short essay and transcript.", deadline:"January 15", link:"https://www.rbcfoundation.com/", tags:["Merit","National","Any Program"] },
  { name:"TD Scholarship for Community Leadership", amount:"$7,500/yr (renewable, up to $30,000)", type:"community", area:"any", prov:"National", desc:"For students who have demonstrated exceptional community involvement alongside strong academic achievement. Includes mentoring and networking.", deadline:"February", link:"https://www.td.com/ca/en/personal-banking/products/scholarships/", tags:["Community","Leadership","Merit","Renewable","National"] },
  { name:"Horatio Alger Canadian Scholarship", amount:"$5,000", type:"need", area:"any", prov:"National", desc:"For students who have overcome personal adversity and demonstrated perseverance and determination to pursue post-secondary education.", deadline:"October 25", link:"https://horatioalger.ca/scholarships/", tags:["Need-Based","Adversity","National","Any Program"] },
  { name:"Ruth Binnie Scholarship (CFUW)", amount:"$1,000+", type:"merit", area:"any", prov:"National", desc:"Awarded to female students who are entering their first year of post-secondary education. One of many CFUW scholarships available.", deadline:"November 1", link:"https://cfuw.org/fellowships-awards/", tags:["Women","Merit","National"] },
  { name:"Governor General's Academic Medal", amount:"Medal + varies", type:"merit", area:"any", prov:"National", desc:"Awarded to the student who achieves the highest academic standing at their high school upon graduation. Opens doors to many university scholarships.", deadline:"Set by school at graduation", link:"https://www.gg.ca/en/honours/canadian-honours/governor-generals-academic-medals", tags:["Merit","Academic","National","High School Award"] },
  { name:"Canada Student Grant for Full-Time Students", amount:"Up to $10,200/yr", type:"need", area:"any", prov:"National", desc:"Non-repayable federal grant for students from low and middle-income families. Applied through your provincial student aid program (e.g., OSAP, StudentAid BC).", deadline:"Apply via provincial portal", link:"https://www.canada.ca/en/employment-social-development/services/student-financial-aid/student-loan/grants.html", tags:["Need-Based","Non-Repayable","Federal","All Students"] },
  { name:"Canada Student Grant for Students with Disabilities", amount:"Up to $4,000/yr", type:"need", area:"any", prov:"National", desc:"Non-repayable grant for students with permanent disabilities attending post-secondary education.", deadline:"Apply via provincial portal", link:"https://www.canada.ca/en/employment-social-development/services/student-financial-aid/student-loan/grants.html", tags:["Disability","Need-Based","Non-Repayable","Federal"] },
  { name:"BMO Celebrating Women Scholarship", amount:"$2,000–$4,000", type:"merit", area:"any", prov:"National", desc:"Supporting women pursuing post-secondary education in any field. Emphasis on leadership and community involvement.", deadline:"February", link:"https://bmo.com/", tags:["Women","Merit","Leadership","National"] },
  { name:"Scotiabank Environmental Scholarship", amount:"$2,500", type:"merit", area:"any", prov:"National", desc:"For students entering programs related to sustainability, environment, or environmental engineering.", deadline:"March", link:"https://www.scotiabank.com/", tags:["Environmental","STEM","Merit","National"] },
  { name:"Thales Canada Scholarship in STEM", amount:"$10,000", type:"stem", area:"eng", prov:"National", desc:"For students entering STEM disciplines with strong academic performance and interest in technology and innovation.", deadline:"March 31", link:"https://www.thalesgroup.com/en/canada", tags:["STEM","Engineering","Technology","Merit"] },
  { name:"Burger King Scholars Program", amount:"$1,000–$5,000", type:"merit", area:"any", prov:"National", desc:"Open to BK employees and their family members, as well as high school graduates at large. Merit and need-based.", deadline:"December 15", link:"https://www.bkscholars.com/", tags:["Merit","Need-Based","National","Any Program"] },
  { name:"CIBC Peter F. Bronfman Business Scholarship", amount:"$5,000", type:"merit", area:"bus", prov:"National", desc:"For students pursuing business programs. Merit-based with emphasis on leadership and academic achievement.", deadline:"March", link:"https://www.cibc.com/", tags:["Business","Merit","Leadership","National"] },
  // ── ONTARIO ──
  { name:"OSAP Grant (Ontario)", amount:"Up to $10,200/yr (non-repayable)", type:"need", area:"any", prov:"Ontario", desc:"Ontario Student Assistance Program — combines grants (non-repayable) and loans. Most students from families earning under $175k receive some grant. Apply early.", deadline:"Apply at ontario.ca/osap (opens summer)", link:"https://www.ontario.ca/page/ontario-student-assistance-program", tags:["Need-Based","Non-Repayable","Provincial","Ontario"] },
  { name:"Ontario First Generation Bursary", amount:"Up to $3,000/yr", type:"need", area:"any", prov:"Ontario", desc:"For students who are the first in their immediate family to attend post-secondary education in Ontario.", deadline:"Via OSAP", link:"https://www.ontario.ca/page/ontario-student-assistance-program", tags:["Need-Based","First-Gen","Ontario","Bursary"] },
  { name:"Ontario Graduate Scholarship", amount:"$15,000 (graduate)", type:"merit", area:"any", prov:"Ontario", desc:"For graduate students (master's or PhD) in Ontario with outstanding academic achievement. Plan ahead if research is your path.", deadline:"Varies by university (fall)", link:"https://www.ontario.ca/page/ontario-graduate-scholarship", tags:["Merit","Graduate","Ontario","Research"] },
  { name:"University of Toronto Excellence Award", amount:"$5,000–$7,500", type:"merit", area:"any", prov:"Ontario", desc:"Automatic for incoming students with 95%+ admission average. No separate application required.", deadline:"Automatic at admission", link:"https://future.utoronto.ca/finances/awards/", tags:["Merit","Automatic","UofT","Ontario"] },
  { name:"University of Toronto National Scholarship", amount:"$10,000–$28,000", type:"merit", area:"any", prov:"Ontario", desc:"For top incoming students — usually top 0.1% nationally. Includes research and leadership opportunities.", deadline:"Invitation only (Nov–Jan)", link:"https://future.utoronto.ca/finances/awards/", tags:["Merit","Top Students","UofT","Invitation"] },
  { name:"Waterloo President's Scholarship", amount:"$2,000", type:"merit", area:"any", prov:"Ontario", desc:"Automatic for incoming students with 95%+ admission average at Waterloo. No separate application.", deadline:"Automatic at admission", link:"https://uwaterloo.ca/student-awards-financial-aid/", tags:["Merit","Automatic","Waterloo","Ontario"] },
  { name:"McMaster National Scholarship", amount:"Up to $24,000 ($6,000/yr × 4)", type:"merit", area:"any", prov:"Ontario", desc:"For exceptional incoming students with very high averages and demonstrated extracurricular excellence.", deadline:"January 15", link:"https://registrar.mcmaster.ca/aid/scholarships/", tags:["Merit","McMaster","Ontario","Renewable"] },
  { name:"Queen's Chancellor's Scholarship", amount:"$36,000 ($9,000/yr × 4)", type:"merit", area:"any", prov:"Ontario", desc:"The most prestigious Queen's entrance scholarship. Awarded to top incoming students with outstanding academic and extracurricular records.", deadline:"January 31", link:"https://www.queensu.ca/registrar/financial-aid/entrance-awards", tags:["Merit","Queen's","Ontario","Top Award"] },
  { name:"Western Scholarship of Distinction", amount:"$2,000", type:"merit", area:"any", prov:"Ontario", desc:"Automatic for incoming students with 90%+ admission average at Western. No separate application.", deadline:"Automatic at admission", link:"https://registrar.uwo.ca/student_finances/scholarships_awards/", tags:["Merit","Automatic","Western","Ontario"] },
  { name:"uOttawa Excellence Scholarship", amount:"$2,000–$4,000", type:"merit", area:"any", prov:"Ontario", desc:"Automatic entrance scholarships for students with high academic standing entering University of Ottawa.", deadline:"Automatic at admission", link:"https://www.uottawa.ca/administration-and-governance/financial-aid-awards/", tags:["Merit","Automatic","uOttawa","Bilingual"] },
  { name:"Carleton University Entrance Scholarship", amount:"$4,000–$8,000", type:"merit", area:"any", prov:"Ontario", desc:"For incoming students with high averages. Various streams for different programs.", deadline:"Automatic + some competitive", link:"https://carleton.ca/awards/", tags:["Merit","Carleton","Ontario"] },
  // ── BRITISH COLUMBIA ──
  { name:"StudentAid BC Grant", amount:"Up to $4,000/yr", type:"need", area:"any", prov:"British Columbia", desc:"BC's need-based grant program. Combined with federal grants, BC students can receive significant non-repayable funding.", deadline:"Apply at studentaidbc.ca", link:"https://studentaidbc.ca/", tags:["Need-Based","Non-Repayable","BC","Provincial"] },
  { name:"UBC Trek Excellence Scholarship", amount:"$4,000", type:"merit", area:"any", prov:"British Columbia", desc:"Automatic for incoming UBC students with high admission average. Renewable based on academic performance.", deadline:"Automatic at admission", link:"https://students.ubc.ca/enrolment/finances/awards-scholarships-bursaries", tags:["Merit","Automatic","UBC","BC","Renewable"] },
  { name:"UBC International Major Entrance Scholarship", amount:"Up to $80,000 over 4 years", type:"merit", area:"any", prov:"British Columbia", desc:"For outstanding international students entering UBC. Highly competitive — top international applicants only.", deadline:"Competitive (Jan 31)", link:"https://students.ubc.ca/enrolment/finances/awards-scholarships-bursaries", tags:["International","Merit","UBC","Top Award"] },
  { name:"SFU Major Entrance Scholarship", amount:"$3,500–$5,000", type:"merit", area:"any", prov:"British Columbia", desc:"For high-achieving students entering SFU full-time. Merit-based with no separate application for most levels.", deadline:"Automatic + competitive stream", link:"https://www.sfu.ca/students/financialaid/entrance/", tags:["Merit","SFU","BC"] },
  { name:"BC Excellence Award", amount:"$5,000", type:"merit", area:"any", prov:"British Columbia", desc:"Awarded by the BC government to outstanding high school graduates entering any BC post-secondary institution.", deadline:"Varies", link:"https://www2.gov.bc.ca/", tags:["Merit","BC","Government","Any Institution"] },
  // ── ALBERTA ──
  { name:"Alberta Student Aid Grant", amount:"Varies (need-based)", type:"need", area:"any", prov:"Alberta", desc:"Alberta's provincial need-based financial aid program. Combines grants and loans for eligible students.", deadline:"Apply at studentaid.alberta.ca", link:"https://studentaid.alberta.ca/", tags:["Need-Based","Alberta","Provincial","Non-Repayable"] },
  { name:"Alexander Rutherford Scholarship", amount:"Up to $2,500", type:"merit", area:"any", prov:"Alberta", desc:"Alberta government scholarship for high school students with strong grades entering post-secondary. Based on grade 10, 11, and 12 marks.", deadline:"Apply online — ongoing", link:"https://studentaid.alberta.ca/scholarships/alexander-rutherford-scholarship/", tags:["Merit","Alberta","Government","Automatic"] },
  { name:"Jason Lang Scholarship", amount:"$1,000/yr (renewal)", type:"merit", area:"any", prov:"Alberta", desc:"Alberta renewal scholarship for students who complete their first year with a GPA of 3.2 or higher at an eligible institution.", deadline:"Apply after first year", link:"https://studentaid.alberta.ca/scholarships/jason-lang-scholarship/", tags:["Merit","Renewable","Alberta","Government"] },
  { name:"U of A Excellence Scholarship", amount:"$2,000–$9,000", type:"merit", area:"any", prov:"Alberta", desc:"Various entrance scholarships at the University of Alberta for students with outstanding academic records.", deadline:"Automatic at admission", link:"https://www.ualberta.ca/registrar/scholarships-awards-financial-support/", tags:["Merit","UAlberta","Alberta"] },
  // ── QUÉBEC ──
  { name:"Aide financière aux études (AFE)", amount:"Varies (need-based)", type:"need", area:"any", prov:"Quebec", desc:"Quebec's provincial financial aid system. Québec residents at Quebec institutions pay extremely low tuition, making additional aid go very far.", deadline:"Apply at afe.gouv.qc.ca", link:"https://www.afe.gouv.qc.ca/", tags:["Need-Based","Quebec","Provincial","French"] },
  { name:"McGill Principal's Scholarships", amount:"$3,000–$20,000/yr", type:"merit", area:"any", prov:"Quebec", desc:"Various entrance scholarships at McGill, including the prestigious Principal's Award for top incoming students.", deadline:"Automatic at admission", link:"https://www.mcgill.ca/studentaid/scholarships/entrance-scholarships", tags:["Merit","McGill","Quebec","Automatic"] },
  { name:"Concordia Merit Scholarship", amount:"$1,000–$5,000", type:"merit", area:"any", prov:"Quebec", desc:"For high-achieving students entering Concordia University. Renewable with maintained GPA.", deadline:"Automatic at admission", link:"https://www.concordia.ca/admissions/scholarships.html", tags:["Merit","Concordia","Quebec","Renewable"] },
  // ── STEM-SPECIFIC ──
  { name:"NSERC Undergraduate Summer Research Awards (USRA)", amount:"$4,500 + employer top-up", type:"stem", area:"eng", prov:"National", desc:"Summer research awards for undergraduates working in NSERC-eligible research groups. Excellent for students interested in grad school or research careers.", deadline:"Varies by institution (Dec–Feb)", link:"https://www.nserc-crsng.gc.ca/students-etudiants/ug-pc/usra-brpc_eng.asp", tags:["Research","STEM","Engineering","Science","National","Summer"] },
  { name:"Mitacs Globalink Research Internship", amount:"$7,500", type:"stem", area:"any", prov:"National", desc:"International research internship program for undergrads. Work with a professor at a top Canadian or international university.", deadline:"September (application opens)", link:"https://www.mitacs.ca/en/programs/globalink", tags:["Research","International","STEM","Internship","National"] },
  { name:"Engineers Canada Scholarships", amount:"$2,500–$5,000", type:"stem", area:"eng", prov:"National", desc:"Various scholarships through Engineers Canada for students in accredited engineering programs across Canada.", deadline:"Varies", link:"https://engineerscanada.ca/", tags:["Engineering","STEM","Merit","National"] },
  { name:"Electrical and Computer Engineering Entrance Award", amount:"Varies by school", type:"stem", area:"eng", prov:"National", desc:"ECE departments at most Canadian universities offer program-specific entrance awards for high-achieving students.", deadline:"Automatic or competitive", link:"https://engineerscanada.ca/", tags:["Engineering","ECE","STEM","Merit"] },
  // ── COMMUNITY / LEADERSHIP ──
  { name:"Historica Canada Heritage Scholarship", amount:"$1,000", type:"community", area:"any", prov:"National", desc:"For students with demonstrated interest and achievement in Canadian history and citizenship education.", deadline:"February", link:"https://www.historicacanada.ca/", tags:["Community","History","National","Leadership"] },
  { name:"Canadian Merit Scholarship Foundation Awards", amount:"$5,000–$18,000", type:"merit", area:"any", prov:"National", desc:"CMSF awards several scholarships annually based on exceptional overall character — not just academics.", deadline:"October", link:"https://www.cmsf.ca/", tags:["Merit","Leadership","National","Character"] },
  { name:"CIBC Youthvision Scholarship", amount:"$1,500", type:"community", area:"any", prov:"National", desc:"Recognizing students who make a difference in their communities through volunteerism and leadership.", deadline:"February", link:"https://www.cibc.com/", tags:["Community","Leadership","Volunteering","National"] },
  { name:"BC Achievement Foundation — Social Innovation Award", amount:"$5,000", type:"community", area:"any", prov:"British Columbia", desc:"For BC students who create innovative solutions to social challenges in their communities.", deadline:"March", link:"https://www.bcachievement.com/", tags:["Community","Innovation","BC","Leadership"] },
  // ── NEED-BASED ──
  { name:"Breakfast Club of Canada Scholarship", amount:"$1,000", type:"need", area:"any", prov:"National", desc:"For students who have overcome food insecurity or economic hardship and are entering post-secondary education.", deadline:"March 31", link:"https://www.breakfastclubcanada.org/", tags:["Need-Based","National","Food Security"] },
  { name:"United Way Scholarship", amount:"Varies by chapter", type:"need", area:"any", prov:"National", desc:"Various scholarships offered by local United Way chapters. Check your local chapter for available awards.", deadline:"Varies by chapter (usually March–April)", link:"https://unitedway.ca/", tags:["Need-Based","Local","Community","National"] },
  { name:"First Nations University of Canada Scholarship", amount:"Varies", type:"need", area:"any", prov:"National", desc:"Various scholarships for Indigenous students, including First Nations, Métis, and Inuit, attending any Canadian university.", deadline:"Varies", link:"https://www.fnuniv.ca/", tags:["Indigenous","Need-Based","National","Cultural"] },
  { name:"Indspire — Building Brighter Futures Bursaries", amount:"$2,000–$4,000", type:"need", area:"any", prov:"National", desc:"Bursaries for First Nations, Métis, and Inuit students pursuing post-secondary education.", deadline:"Ongoing (rolling applications)", link:"https://indspire.ca/programs/", tags:["Indigenous","Need-Based","National","Bursary"] },
];

// Export for use in other pages
if (typeof module !== 'undefined') {
  module.exports = { MAJORS, UNIVERSITIES, PROGRAM_DATA, GRADE12_COURSES, SCHOLARSHIPS };
}
